"""
F-02 / FR-103: Statistical Validator for AI Market Insights
Evaluates hypotheses generated by LLM against real historical ClosedTrade data.
Enforces strict Anti-Small-Sample Guard to prevent false positive conclusions.
"""
import logging
import math
import uuid
from datetime import datetime, timezone
from typing import List, Dict, Any, Tuple, Optional
from scipy.stats import norm

from app.core.config import settings
from app.domain.models import ClosedTrade, MarketInsight

import ast

logger = logging.getLogger(__name__)

# Allowed AST Operators & Nodes for safe evaluation
ALLOWED_OPERATORS = {
    ast.Eq: lambda a, b: a == b,
    ast.NotEq: lambda a, b: a != b,
    ast.Lt: lambda a, b: a < b,
    ast.LtE: lambda a, b: a <= b,
    ast.Gt: lambda a, b: a > b,
    ast.GtE: lambda a, b: a >= b,
    ast.Add: lambda a, b: a + b,
    ast.Sub: lambda a, b: a - b,
    ast.Mult: lambda a, b: a * b,
    ast.Div: lambda a, b: a / b if b != 0 else 0,
}

ALLOWED_UNARY_OPERATORS = {
    ast.USub: lambda a: -a,
    ast.UAdd: lambda a: +a,
    ast.Not: lambda a: not a,
}


def _safe_eval_ast_node(node: ast.AST, context: Dict[str, Any]) -> Any:
    if isinstance(node, ast.Expression):
        return _safe_eval_ast_node(node.body, context)
    elif isinstance(node, ast.Constant):
        return node.value
    elif isinstance(node, (ast.Num, ast.Str, ast.NameConstant)):  # Compat
        return getattr(node, 'value', getattr(node, 'n', getattr(node, 's', None)))
    elif isinstance(node, ast.Name):
        if node.id in context:
            return context[node.id]
        raise ValueError(f"Variable '{node.id}' is not an allowed trade context attribute")
    elif isinstance(node, ast.UnaryOp):
        op_type = type(node.op)
        if op_type not in ALLOWED_UNARY_OPERATORS:
            raise ValueError(f"Unary operator {op_type.__name__} is not allowed")
        operand = _safe_eval_ast_node(node.operand, context)
        return ALLOWED_UNARY_OPERATORS[op_type](operand)
    elif isinstance(node, ast.BinOp):
        op_type = type(node.op)
        if op_type not in ALLOWED_OPERATORS:
            raise ValueError(f"Binary operator {op_type.__name__} is not allowed")
        left = _safe_eval_ast_node(node.left, context)
        right = _safe_eval_ast_node(node.right, context)
        return ALLOWED_OPERATORS[op_type](left, right)
    elif isinstance(node, ast.BoolOp):
        if type(node.op) is ast.And:
            for value_node in node.values:
                if not _safe_eval_ast_node(value_node, context):
                    return False
            return True
        elif type(node.op) is ast.Or:
            for value_node in node.values:
                if _safe_eval_ast_node(value_node, context):
                    return True
            return False
        else:
            raise ValueError(f"Boolean operator {type(node.op).__name__} is not allowed")
    elif isinstance(node, ast.Compare):
        left = _safe_eval_ast_node(node.left, context)
        for op, comparator in zip(node.ops, node.comparators):
            op_type = type(op)
            if op_type not in ALLOWED_OPERATORS:
                raise ValueError(f"Comparison operator {op_type.__name__} is not allowed")
            right = _safe_eval_ast_node(comparator, context)
            if not ALLOWED_OPERATORS[op_type](left, right):
                return False
            left = right
        return True
    else:
        raise ValueError(f"Disallowed AST node type: {type(node).__name__}")


def safe_eval_condition(condition_str: str, context: Dict[str, Any]) -> bool:
    """
    Safely parses and evaluates a boolean comparison expression without eval().
    Strictly forbids function calls, attribute access, subscripts, and imports.
    """
    parsed_ast = ast.parse(condition_str, mode='eval')
    res = _safe_eval_ast_node(parsed_ast, context)
    return bool(res)


def _evaluate_trade_condition(trade: ClosedTrade, condition_str: str) -> Optional[bool]:
    """
    Safely evaluates a trade hypothesis condition string against ClosedTrade attributes.
    """
    try:
        trade_context = {
            "confidence_score": float(trade.confidence_score),
            "holding_time_minutes": float(trade.holding_time_minutes),
            "position_size_usd": float(trade.position_size_usd),
            "risk_pct": float(trade.risk_pct),
            "pnl_pct_actual": float(trade.pnl_pct_actual),
            "r_multiple": float(trade.r_multiple),
            "exit_reason": str(trade.exit_reason),
            "is_paper_trade": bool(trade.is_paper_trade),
            "is_bootstrap": bool(trade.is_bootstrap),
            "label": str(trade.label),
            "direction": str(trade.direction)
        }
        res = safe_eval_condition(condition_str, trade_context)
        return res
    except Exception as e:
        logger.debug(f"[STATISTICAL VALIDATOR] Failed to safely evaluate condition '{condition_str}' on trade {trade.trade_id}: {e}")
        return None


def calculate_two_proportion_z_pvalue(success_a: int, n_a: int, success_b: int, n_b: int) -> float:
    """
    Calculates two-tailed p-value for two independent proportion Z-test.
    """
    if n_a <= 0 or n_b <= 0:
        return 1.0
    p_a = success_a / n_a
    p_b = success_b / n_b
    p_pool = (success_a + success_b) / (n_a + n_b)
    
    se = math.sqrt(p_pool * (1 - p_pool) * ((1 / n_a) + (1 / n_b)))
    if se == 0:
        return 1.0 if p_a == p_b else 0.0
    z = (p_a - p_b) / se
    p_val = 2 * (1 - norm.cdf(abs(z)))
    return float(p_val)


class StatisticalValidator:
    """
    FR-103: Automated Statistical Validator Engine
    """
    def __init__(self, min_sample_per_group: Optional[int] = None):
        self.min_sample_per_group = min_sample_per_group or getattr(settings, "INSIGHT_MIN_SAMPLE_PER_GROUP", 10)

    def validate_hypothesis(
        self,
        hypothesis_text: str,
        affected_condition: str,
        trades: List[ClosedTrade]
    ) -> MarketInsight:
        """
        Splits trades into Group A (condition met) and Group B (condition not met),
        calculates win rates, expectancy, p-value, and assigns statistical status.
        """
        now = datetime.now(timezone.utc)
        insight_id = f"ins_{uuid.uuid4().hex[:10]}"

        if not trades:
            return MarketInsight(
                insight_id=insight_id,
                hypothesis_text=hypothesis_text,
                affected_condition=affected_condition,
                sample_size_group_a=0,
                sample_size_group_b=0,
                win_rate_group_a=0.0,
                win_rate_group_b=0.0,
                win_rate_diff=0.0,
                expectancy_group_a=0.0,
                expectancy_group_b=0.0,
                expectancy_diff=0.0,
                statistical_p_value=None,
                statistical_status="INSUFFICIENT_DATA",
                rejection_reason="No historical trade data available for validation.",
                created_at=now
            )

        group_a: List[ClosedTrade] = []
        group_b: List[ClosedTrade] = []
        invalid_eval_count = 0

        for t in trades:
            eval_res = _evaluate_trade_condition(t, affected_condition)
            if eval_res is True:
                group_a.append(t)
            elif eval_res is False:
                group_b.append(t)
            else:
                invalid_eval_count += 1

        # Check if condition expression was completely unparseable
        if invalid_eval_count == len(trades):
            return MarketInsight(
                insight_id=insight_id,
                hypothesis_text=hypothesis_text,
                affected_condition=affected_condition,
                sample_size_group_a=0,
                sample_size_group_b=0,
                win_rate_group_a=0.0,
                win_rate_group_b=0.0,
                win_rate_diff=0.0,
                expectancy_group_a=0.0,
                expectancy_group_b=0.0,
                expectancy_diff=0.0,
                statistical_p_value=None,
                statistical_status="INSUFFICIENT_DATA",
                rejection_reason=f"Condition expression '{affected_condition}' cannot be evaluated against trade data fields.",
                created_at=now
            )

        n_a = len(group_a)
        n_b = len(group_b)

        wins_a = sum(1 for t in group_a if t.label == "BUY_BENAR" or t.r_multiple > 0)
        wins_b = sum(1 for t in group_b if t.label == "BUY_BENAR" or t.r_multiple > 0)

        win_rate_a = (wins_a / n_a) if n_a > 0 else 0.0
        win_rate_b = (wins_b / n_b) if n_b > 0 else 0.0
        win_rate_diff = win_rate_a - win_rate_b

        exp_a = (sum(t.r_multiple for t in group_a) / n_a) if n_a > 0 else 0.0
        exp_b = (sum(t.r_multiple for t in group_b) / n_b) if n_b > 0 else 0.0
        exp_diff = exp_a - exp_b

        p_value = calculate_two_proportion_z_pvalue(wins_a, n_a, wins_b, n_b) if (n_a > 0 and n_b > 0) else None

        # FR-103 Anti-Small-Sample Guard
        if n_a < self.min_sample_per_group or n_b < self.min_sample_per_group:
            reason = (
                f"Sample size below minimum threshold (Group A N={n_a}, Group B N={n_b}, "
                f"Required N={self.min_sample_per_group})."
            )
            logger.info(f"[STATISTICAL VALIDATOR] [REJECTED] {hypothesis_text} -> {reason}")
            return MarketInsight(
                insight_id=insight_id,
                hypothesis_text=hypothesis_text,
                affected_condition=affected_condition,
                sample_size_group_a=n_a,
                sample_size_group_b=n_b,
                win_rate_group_a=win_rate_a,
                win_rate_group_b=win_rate_b,
                win_rate_diff=win_rate_diff,
                expectancy_group_a=exp_a,
                expectancy_group_b=exp_b,
                expectancy_diff=exp_diff,
                statistical_p_value=p_value,
                statistical_status="REJECTED_STATISTICAL",
                rejection_reason=reason,
                created_at=now
            )

        # Statistical significance criteria: positive win rate diff & expectancy diff and p_value <= 0.10
        is_significant = (win_rate_diff >= 0.05 or exp_diff >= 0.15) and (p_value is not None and p_value <= 0.10)

        if is_significant:
            logger.info(
                f"[STATISTICAL VALIDATOR] [PASSED] Hypothesis '{hypothesis_text}' "
                f"passed statistical gating (N_A={n_a}, N_B={n_b}, dWR={win_rate_diff:+.1%}, dExp={exp_diff:+.2f}R, p={p_value:.4f})."
            )
            return MarketInsight(
                insight_id=insight_id,
                hypothesis_text=hypothesis_text,
                affected_condition=affected_condition,
                sample_size_group_a=n_a,
                sample_size_group_b=n_b,
                win_rate_group_a=win_rate_a,
                win_rate_group_b=win_rate_b,
                win_rate_diff=win_rate_diff,
                expectancy_group_a=exp_a,
                expectancy_group_b=exp_b,
                expectancy_diff=exp_diff,
                statistical_p_value=p_value,
                statistical_status="PENDING_REVIEW",
                rejection_reason=None,
                created_at=now
            )
        else:
            reason = (
                f"Difference not statistically significant (dWR={win_rate_diff:+.1%}, "
                f"dExp={exp_diff:+.2f}R, p-value={p_value:.4f} > 0.10)."
            )
            logger.info(f"[STATISTICAL VALIDATOR] [REJECTED] {hypothesis_text} -> {reason}")
            return MarketInsight(
                insight_id=insight_id,
                hypothesis_text=hypothesis_text,
                affected_condition=affected_condition,
                sample_size_group_a=n_a,
                sample_size_group_b=n_b,
                win_rate_group_a=win_rate_a,
                win_rate_group_b=win_rate_b,
                win_rate_diff=win_rate_diff,
                expectancy_group_a=exp_a,
                expectancy_group_b=exp_b,
                expectancy_diff=exp_diff,
                statistical_p_value=p_value,
                statistical_status="REJECTED_STATISTICAL",
                rejection_reason=reason,
                created_at=now
            )
